changesDir: .changes
unreleasedDir: unreleased
headerPath: ../.chglog/CHANGELOG_HEADER.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
newlines:
  afterChangelogHeader: 0
  beforeChangelogVersion: 1
  endOfVersion: 1
replacements:
  - path: "package.json"
    find: '"version": ".*"'
    replace: '"version": "{{.VersionNoPrefix}}"'
