name: deploy_to_netlify

on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize
      - closed

env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  DEPLOY_DIR: dist

jobs:
  set_deploy_environment:
    if: github.event.action != 'closed' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Set deploy environment as pr-${{ github.event.number }}-preview
        if: github.base_ref == 'develop' && contains(fromJSON('["opened", "synchronize"]'), github.event.action)
        env:
          DEPLOY_ENVIRONMENT: pr-${{ github.event.number }}-preview
        run: echo "DEPLOY_ENVIRONMENT=$DEPLOY_ENVIRONMENT" >> $GITHUB_ENV

      - name: Set deploy environment as preview
        if: github.base_ref == 'develop' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: echo "DEPLOY_ENVIRONMENT=preview" >> $GITHUB_ENV

      - name: Set deploy environment as staging
        if: github.base_ref == 'main' && contains(fromJSON('["opened", "synchronize"]'), github.event.action)
        run: echo "DEPLOY_ENVIRONMENT=staging" >> $GITHUB_ENV

      - name: Set deploy environment as production
        if: github.base_ref == 'main' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: echo "DEPLOY_ENVIRONMENT=production" >> $GITHUB_ENV

      - name: Set deploy environment output
        id: deploy_environment
        run: |
          echo "github_environment=$DEPLOY_ENVIRONMENT" >> $GITHUB_OUTPUT

    outputs:
      github_environment: ${{ steps.deploy_environment.outputs.github_environment }}

  deploy:
    if: github.event.action != 'closed' || github.event.pull_request.merged == true
    needs: set_deploy_environment
    environment:
      name: ${{ needs.set_deploy_environment.outputs.github_environment }}
      url: ${{ steps.post_deploy.outputs.netlify_draft_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Get PNPM store directory
        id: pnpm-cache
        run: echo "pnpm_store_path=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_store_path }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install Netlify CLI
        run: pnpm add --save-dev netlify-cli

      - name: Set as Netlify production deployment
        if: needs.set_deploy_environment.outputs.github_environment == 'production'
        run: echo "PROD=true" >> $GITHUB_ENV

      - name: Deploy preview
        id: deploy
        if: success()
        env:
          DEPLOY_PREFIX: pr-${{ github.event.number }}--
          DEPLOY_ALIAS: pr-${{ github.event.number }}
        shell: bash
        run: |
          set -e
          OUTPUT=$(pnpm netlify deploy \
            --auth ${{ env.NETLIFY_AUTH_TOKEN }} \
            --site ${{ env.NETLIFY_SITE_ID }} \
            --json \
            --build \
            --context deploy-preview \
            --alias ${DEPLOY_ALIAS} \
            --message "$(git log -1 --pretty=%s)" \
            --prod ${PROD:-false} \
            | tr '\n' ' ')
          set +e

          NETLIFY_OUTPUT=$(echo "$OUTPUT")

          echo "netlify_output=$NETLIFY_OUTPUT" >> $GITHUB_OUTPUT

      - name: Post deploy
        id: post_deploy
        if: success()
        env:
          NETLIFY_LOGS_URL: ${{ fromJson(steps.deploy.outputs.netlify_output).logs }}
          NETLIFY_DRAFT_URL: ${{ fromJson(steps.deploy.outputs.netlify_output).deploy_url }}
          NETLIFY_PROD_URL: ${{ fromJson(steps.deploy.outputs.netlify_output).url }}
        run: |
          echo "netlify_logs_url=$NETLIFY_LOGS_URL" >> $GITHUB_OUTPUT
          echo "netlify_draft_url=$NETLIFY_DRAFT_URL" >> $GITHUB_OUTPUT
          echo "netlify_prod_url=$NETLIFY_PROD_URL" >> $GITHUB_OUTPUT
