name: deploy-preview

on:
  pull_request:
    branches:
      - main
      - develop

env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  DEPLOY_DIR: dist

jobs:
  deploy-preview:
    environment:
      name: ${{ steps.post_deploy.outputs.github_environment }}
      url: ${{ steps.post_deploy.outputs.netlify_draft_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Get PNPM store directory
        id: pnpm-cache
        run: echo "pnpm_store_path=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_store_path }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install Netlify CLI
        run: pnpm add --save-dev netlify-cli

      - name: Set deploy environment for ${{ github.base_ref }} branch
        if: github.base_ref == 'main'
        run: |
          echo "DEPLOY_ENV=staging" >> $GITHUB_ENV

      - name: Set deploy environment for ${{ github.base_ref }} branch
        if: github.base_ref == 'develop'
        run: |
          echo "DEPLOY_ENV=preview" >> $GITHUB_ENV

      - name: Deploy preview
        id: deploy
        if: success()
        env:
          DEPLOY_PREFIX: pr-${{ github.event.number }}--
          DEPLOY_ALIAS: pr-${{ github.event.number }}
        shell: bash
        run: |
          set -e
          OUTPUT=$(pnpm netlify deploy \
            --auth ${{ env.NETLIFY_AUTH_TOKEN }} \
            --site ${{ env.NETLIFY_SITE_ID }} \
            --json \
            --build \
            --context deploy-preview \
            --alias ${DEPLOY_ALIAS} \
            --message "$(git log -1 --pretty=%B)" \
            | tr '\n' ' ')
          set +e

          NETLIFY_OUTPUT=$(echo "$OUTPUT")

          echo "netlify_output=$NETLIFY_OUTPUT" >> $GITHUB_OUTPUT

      - name: Post deploy
        id: post_deploy
        if: success()
        env:
          NETLIFY_LOGS_URL: ${{ fromJson(steps.deploy.outputs.netlify_output).logs }}
          NETLIFY_DRAFT_URL: ${{ fromJson(steps.deploy.outputs.netlify_output).deploy_url }}
          NETLIFY_PROD_URL: ${{ fromJson(steps.deploy.outputs.netlify_output).url }}
        run: |
          echo "netlify_logs_url=$NETLIFY_LOGS_URL" >> $GITHUB_OUTPUT
          echo "netlify_draft_url=$NETLIFY_DRAFT_URL" >> $GITHUB_OUTPUT
          echo "netlify_prod_url=$NETLIFY_PROD_URL" >> $GITHUB_OUTPUT

          echo "github_environment=$DEPLOY_ENV" >> $GITHUB_OUTPUT
