name: merge_release_into_develop

on:
  pull_request:
    types:
      - opened
    branches:
      - develop

jobs:
  merge_release_into_develop:
    name: Merge release into develop
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # only merge pull requests that begin with 'release/' or 'hotfix/'
    if: |
      startsWith(github.head_ref, 'release/') ||
      startsWith(github.head_ref, 'hotfix/')

    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}
          # needed by "gh pr create"
          fetch-depth: 0

      - name: Merge ${{ github.head_ref }} into develop
        uses: ghacts/gitflow/merge-release-into-develop@main
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-branch: ${{ github.head_ref }}
          develop-branch: develop
